# SPDX-FileCopyrightText: 2020 Serokell <https://serokell.io/>
#
# SPDX-License-Identifier: MPL-2.0

resolver: lts-18.18
packages:
  - secure-memory
  - NaCl
  - crypto-sodium
  - crypto-sodium-streamly

extra-deps:
  - libsodium-1.0.18.2

  # Required for GHC >= 9
  #- basement-0.0.12
  - memory-0.16.0
  - streamly-0.8.0

  # Required for GHC >= 9.2
  - basement-0.0.12 # + patch
  - hashable-1.3.5.0
  - random-1.2.1

nix:
  packages:
    - pkgconfig
    - libsodium

    # new streamly wants this
    # - darwin.apple_sdk.frameworks.Cocoa
