# SPDX-FileCopyrightText: 2020 Serokell <https://serokell.io/>
#
# SPDX-License-Identifier: MPL-2.0

resolver: lts-21.0
packages:
  - secure-memory
  - NaCl
  - crypto-sodium

extra-deps:
  - libsodium-1.0.18.3

  # Required for GHC >= 9
  - basement-0.0.16
  - memory-0.18.0
  - streamly-0.9.0

  # Required for GHC >= 9.2
  #- basement-???
  #- hashable-1.3.5.0

nix:
  packages:
    - pkgconfig
    - libsodium

    # new streamly wants this
    # - darwin.apple_sdk.frameworks.Cocoa
