# SPDX-FileCopyrightText: 2020 Serokell <https://serokell.io/>
#
# SPDX-License-Identifier: MPL-2.0

- &version
  version: 0.0.5.0

- &author
  author: Kirill Elagin <kirelagin@serokell.io>
  maintainer: Serokell <libraries@serokell.io>
  copyright: 2021 Serokell
  license-file: LICENSES/MPL-2.0.txt

  github: serokell/haskell-crypto

- &defaults
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

  default-extensions:
    - DataKinds
    - FlexibleContexts
    - FlexibleInstances
    - GeneralizedNewtypeDeriving
    - KindSignatures
    - LambdaCase
    - MultiParamTypeClasses
    - NamedFieldPuns
    - NumericUnderscores
    - OverloadedStrings
    - PolyKinds
    - ScopedTypeVariables
    - TypeApplications

  dependencies:
    - base >= 4.10 && < 4.18
    - bytestring >= 0.9 && < 0.12
    - libsodium >= 1.0.11 && < 2
    - memory >= 0.14.15 && < 0.19
    - safe-exceptions >= 0.1 && < 0.2

- &lib
  source-dirs: lib

- &test
  source-dirs: test
  main: Test.hs
