# SPDX-FileCopyrightText: 2020 Serokell <https://serokell.io/>
#
# SPDX-License-Identifier: MPL-2.0

_common: !include "../hpack/package.yaml"

name: crypto-sodium
<<: *version
synopsis: Easy-and-safe-to-use high-level cryptography based on Sodium
description: |
  This is a collection of high-level cryptographic primitives based on
  <https://libsodium.io/ Sodium>, spiced up with extra type-safety
  of the Haskell type system.

  __Note: this package is experimental and WIP.__

  = Why

  Cryptography is hard to do right and you should never try to implement it
  on your own, even if you have access to safe and secure cryptographic
  primitives. Luckily, D. J. Bernstein created <https://nacl.cr.yp.to/ NaCl>.

  NaCl was designed specifically to make it hard to use it incorrectly and
  thus save you from a disaster. It exposes high-level cryptographic
  algorithms with underlying implementations chosen for you, so you do not
  get flexibility, but you get security, which is more important.

  = What

  <https://libsodium.org Sodium> is a reimplementation of NaCl
  with the goal to make it more portable across different platforms.
  With time, it started providing more than the same interface as NaCl.
  Nowadays it implements additional primitives and utility functions.

  = How

  == Library initialisation

  * "Crypto.Init"

  == Secret-key cryptography

  * Authenticated symmetric-key encryption: "Crypto.Encrypt.Symmetric"
  * Message authentication codes: "Crypto.Mac" and "Crypto.Mac.Lazy"

  == Public-key cryptography

  * Authenticated public-key encryption: "Crypto.Encrypt.Public"
  * Public-key signatures: "Crypto.Sign"

  == Additional primitives

  * Key derivation and generation: "Crypto.Key"
  * Cryptographically-secure random: "Crypto.Random"

category: Cryptography

<<: *author

extra-doc-files:
  - CHANGELOG.md
  - README.md

<<: *defaults

library:
  <<: *lib

  dependencies:
    - cereal >= 0.1 && < 0.6
    - NaCl >= 0.0.1.0 && < 0.1
    - random >= 1.0 && < 1.2

tests:
  test:
    <<: *test

    dependencies:
      - crypto-sodium

      - hedgehog
      - HUnit
      - tasty
      - tasty-hedgehog
      - tasty-hunit

      - base16-bytestring
      - deepseq

    build-tools:
      - tasty-discover:tasty-discover
